// Basic Proto file. In this example, we would just be returning the Codename based on the Input version.
// Example. /ListAll to return all /ListOne(2025.3.0) ==> Uvas, Etc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: Version.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbsoluteVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // These indices would be used to encode the req as protobuf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsoluteVersion) Reset() {
	*x = AbsoluteVersion{}
	mi := &file_Version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsoluteVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsoluteVersion) ProtoMessage() {}

func (x *AbsoluteVersion) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsoluteVersion.ProtoReflect.Descriptor instead.
func (*AbsoluteVersion) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{0}
}

func (x *AbsoluteVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Codename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Codename      string                 `protobuf:"bytes,2,opt,name=codename,proto3" json:"codename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Codename) Reset() {
	*x = Codename{}
	mi := &file_Version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Codename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Codename) ProtoMessage() {}

func (x *Codename) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Codename.ProtoReflect.Descriptor instead.
func (*Codename) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{1}
}

func (x *Codename) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Codename) GetCodename() string {
	if x != nil {
		return x.Codename
	}
	return ""
}

var File_Version_proto protoreflect.FileDescriptor

const file_Version_proto_rawDesc = "" +
	"\n" +
	"\rVersion.proto\x12\vVersionInfo\"+\n" +
	"\x0fabsoluteVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"@\n" +
	"\bCodename\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1a\n" +
	"\bcodename\x18\x02 \x01(\tR\bcodename2\x99\x01\n" +
	"\vversionInfo\x12B\n" +
	"\vgetCodeName\x12\x1c.VersionInfo.absoluteVersion\x1a\x15.VersionInfo.Codename\x12F\n" +
	"\x0fgetAbsoluteName\x12\x15.VersionInfo.Codename\x1a\x1c.VersionInfo.absoluteVersionB\x0fZ\r./Intro_pb;pbb\x06proto3"

var (
	file_Version_proto_rawDescOnce sync.Once
	file_Version_proto_rawDescData []byte
)

func file_Version_proto_rawDescGZIP() []byte {
	file_Version_proto_rawDescOnce.Do(func() {
		file_Version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Version_proto_rawDesc), len(file_Version_proto_rawDesc)))
	})
	return file_Version_proto_rawDescData
}

var file_Version_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Version_proto_goTypes = []any{
	(*AbsoluteVersion)(nil), // 0: VersionInfo.absoluteVersion
	(*Codename)(nil),        // 1: VersionInfo.Codename
}
var file_Version_proto_depIdxs = []int32{
	0, // 0: VersionInfo.versionInfo.getCodeName:input_type -> VersionInfo.absoluteVersion
	1, // 1: VersionInfo.versionInfo.getAbsoluteName:input_type -> VersionInfo.Codename
	1, // 2: VersionInfo.versionInfo.getCodeName:output_type -> VersionInfo.Codename
	0, // 3: VersionInfo.versionInfo.getAbsoluteName:output_type -> VersionInfo.absoluteVersion
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Version_proto_init() }
func file_Version_proto_init() {
	if File_Version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Version_proto_rawDesc), len(file_Version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Version_proto_goTypes,
		DependencyIndexes: file_Version_proto_depIdxs,
		MessageInfos:      file_Version_proto_msgTypes,
	}.Build()
	File_Version_proto = out.File
	file_Version_proto_goTypes = nil
	file_Version_proto_depIdxs = nil
}
