// Basic Proto file. In this example, we would just be returning the Codename based on the Input version.
// Example. /ListAll to return all /ListOne(2025.3.0) ==> Uvas, Etc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: Version.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbsoluteVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // These indices would be used to encode the req as protobuf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsoluteVersion) Reset() {
	*x = AbsoluteVersion{}
	mi := &file_Version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsoluteVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsoluteVersion) ProtoMessage() {}

func (x *AbsoluteVersion) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsoluteVersion.ProtoReflect.Descriptor instead.
func (*AbsoluteVersion) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{0}
}

func (x *AbsoluteVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Codename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Codename      string                 `protobuf:"bytes,2,opt,name=codename,proto3" json:"codename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Codename) Reset() {
	*x = Codename{}
	mi := &file_Version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Codename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Codename) ProtoMessage() {}

func (x *Codename) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Codename.ProtoReflect.Descriptor instead.
func (*Codename) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{1}
}

func (x *Codename) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Codename) GetCodename() string {
	if x != nil {
		return x.Codename
	}
	return ""
}

type Nil struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nil) Reset() {
	*x = Nil{}
	mi := &file_Version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{2}
}

type VerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cn            *Codename              `protobuf:"bytes,1,opt,name=cn,proto3" json:"cn,omitempty"`
	Ab            *AbsoluteVersion       `protobuf:"bytes,2,opt,name=ab,proto3" json:"ab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerInfo) Reset() {
	*x = VerInfo{}
	mi := &file_Version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerInfo) ProtoMessage() {}

func (x *VerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerInfo.ProtoReflect.Descriptor instead.
func (*VerInfo) Descriptor() ([]byte, []int) {
	return file_Version_proto_rawDescGZIP(), []int{3}
}

func (x *VerInfo) GetCn() *Codename {
	if x != nil {
		return x.Cn
	}
	return nil
}

func (x *VerInfo) GetAb() *AbsoluteVersion {
	if x != nil {
		return x.Ab
	}
	return nil
}

var File_Version_proto protoreflect.FileDescriptor

const file_Version_proto_rawDesc = "" +
	"\n" +
	"\rVersion.proto\x12\vVersionInfo\"+\n" +
	"\x0fabsoluteVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"@\n" +
	"\bCodename\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1a\n" +
	"\bcodename\x18\x02 \x01(\tR\bcodename\"\x05\n" +
	"\x03nil\"^\n" +
	"\aVerInfo\x12%\n" +
	"\x02cn\x18\x01 \x01(\v2\x15.VersionInfo.CodenameR\x02cn\x12,\n" +
	"\x02ab\x18\x02 \x01(\v2\x1c.VersionInfo.absoluteVersionR\x02ab2\xd0\x01\n" +
	"\vversionInfo\x12B\n" +
	"\vGetCodeName\x12\x1c.VersionInfo.absoluteVersion\x1a\x15.VersionInfo.Codename\x12F\n" +
	"\x0fGetAbsoluteName\x12\x15.VersionInfo.Codename\x1a\x1c.VersionInfo.absoluteVersion\x125\n" +
	"\vAddCodeName\x12\x14.VersionInfo.VerInfo\x1a\x10.VersionInfo.nilB\x0fZ\r./Intro_pb;pbb\x06proto3"

var (
	file_Version_proto_rawDescOnce sync.Once
	file_Version_proto_rawDescData []byte
)

func file_Version_proto_rawDescGZIP() []byte {
	file_Version_proto_rawDescOnce.Do(func() {
		file_Version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Version_proto_rawDesc), len(file_Version_proto_rawDesc)))
	})
	return file_Version_proto_rawDescData
}

var file_Version_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Version_proto_goTypes = []any{
	(*AbsoluteVersion)(nil), // 0: VersionInfo.absoluteVersion
	(*Codename)(nil),        // 1: VersionInfo.Codename
	(*Nil)(nil),             // 2: VersionInfo.nil
	(*VerInfo)(nil),         // 3: VersionInfo.VerInfo
}
var file_Version_proto_depIdxs = []int32{
	1, // 0: VersionInfo.VerInfo.cn:type_name -> VersionInfo.Codename
	0, // 1: VersionInfo.VerInfo.ab:type_name -> VersionInfo.absoluteVersion
	0, // 2: VersionInfo.versionInfo.GetCodeName:input_type -> VersionInfo.absoluteVersion
	1, // 3: VersionInfo.versionInfo.GetAbsoluteName:input_type -> VersionInfo.Codename
	3, // 4: VersionInfo.versionInfo.AddCodeName:input_type -> VersionInfo.VerInfo
	1, // 5: VersionInfo.versionInfo.GetCodeName:output_type -> VersionInfo.Codename
	0, // 6: VersionInfo.versionInfo.GetAbsoluteName:output_type -> VersionInfo.absoluteVersion
	2, // 7: VersionInfo.versionInfo.AddCodeName:output_type -> VersionInfo.nil
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Version_proto_init() }
func file_Version_proto_init() {
	if File_Version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Version_proto_rawDesc), len(file_Version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Version_proto_goTypes,
		DependencyIndexes: file_Version_proto_depIdxs,
		MessageInfos:      file_Version_proto_msgTypes,
	}.Build()
	File_Version_proto = out.File
	file_Version_proto_goTypes = nil
	file_Version_proto_depIdxs = nil
}
