// Basic Proto file. In this example, we would just be returning the Codename based on the Input version.
// Example. /ListAll to return all /ListOne(2025.3.0) ==> Uvas, Etc

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: Version.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VersionInfo_GetCodeName_FullMethodName     = "/VersionInfo.versionInfo/GetCodeName"
	VersionInfo_GetAbsoluteName_FullMethodName = "/VersionInfo.versionInfo/GetAbsoluteName"
	VersionInfo_AddCodeName_FullMethodName     = "/VersionInfo.versionInfo/AddCodeName"
)

// VersionInfoClient is the client API for VersionInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersionInfoClient interface {
	GetCodeName(ctx context.Context, in *AbsoluteVersion, opts ...grpc.CallOption) (*Codename, error)
	GetAbsoluteName(ctx context.Context, in *Codename, opts ...grpc.CallOption) (*AbsoluteVersion, error)
	AddCodeName(ctx context.Context, in *VerInfo, opts ...grpc.CallOption) (*Nil, error)
}

type versionInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionInfoClient(cc grpc.ClientConnInterface) VersionInfoClient {
	return &versionInfoClient{cc}
}

func (c *versionInfoClient) GetCodeName(ctx context.Context, in *AbsoluteVersion, opts ...grpc.CallOption) (*Codename, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Codename)
	err := c.cc.Invoke(ctx, VersionInfo_GetCodeName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionInfoClient) GetAbsoluteName(ctx context.Context, in *Codename, opts ...grpc.CallOption) (*AbsoluteVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbsoluteVersion)
	err := c.cc.Invoke(ctx, VersionInfo_GetAbsoluteName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionInfoClient) AddCodeName(ctx context.Context, in *VerInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, VersionInfo_AddCodeName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionInfoServer is the server API for VersionInfo service.
// All implementations must embed UnimplementedVersionInfoServer
// for forward compatibility.
type VersionInfoServer interface {
	GetCodeName(context.Context, *AbsoluteVersion) (*Codename, error)
	GetAbsoluteName(context.Context, *Codename) (*AbsoluteVersion, error)
	AddCodeName(context.Context, *VerInfo) (*Nil, error)
	mustEmbedUnimplementedVersionInfoServer()
}

// UnimplementedVersionInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVersionInfoServer struct{}

func (UnimplementedVersionInfoServer) GetCodeName(context.Context, *AbsoluteVersion) (*Codename, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeName not implemented")
}
func (UnimplementedVersionInfoServer) GetAbsoluteName(context.Context, *Codename) (*AbsoluteVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAbsoluteName not implemented")
}
func (UnimplementedVersionInfoServer) AddCodeName(context.Context, *VerInfo) (*Nil, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCodeName not implemented")
}
func (UnimplementedVersionInfoServer) mustEmbedUnimplementedVersionInfoServer() {}
func (UnimplementedVersionInfoServer) testEmbeddedByValue()                     {}

// UnsafeVersionInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionInfoServer will
// result in compilation errors.
type UnsafeVersionInfoServer interface {
	mustEmbedUnimplementedVersionInfoServer()
}

func RegisterVersionInfoServer(s grpc.ServiceRegistrar, srv VersionInfoServer) {
	// If the following call panics, it indicates UnimplementedVersionInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VersionInfo_ServiceDesc, srv)
}

func _VersionInfo_GetCodeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbsoluteVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionInfoServer).GetCodeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionInfo_GetCodeName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionInfoServer).GetCodeName(ctx, req.(*AbsoluteVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionInfo_GetAbsoluteName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Codename)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionInfoServer).GetAbsoluteName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionInfo_GetAbsoluteName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionInfoServer).GetAbsoluteName(ctx, req.(*Codename))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionInfo_AddCodeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionInfoServer).AddCodeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionInfo_AddCodeName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionInfoServer).AddCodeName(ctx, req.(*VerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionInfo_ServiceDesc is the grpc.ServiceDesc for VersionInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VersionInfo.versionInfo",
	HandlerType: (*VersionInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCodeName",
			Handler:    _VersionInfo_GetCodeName_Handler,
		},
		{
			MethodName: "GetAbsoluteName",
			Handler:    _VersionInfo_GetAbsoluteName_Handler,
		},
		{
			MethodName: "AddCodeName",
			Handler:    _VersionInfo_AddCodeName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Version.proto",
}
